/* RGD SDBoot Installer */

/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

/* -------------------------------------------------------------------------------- */
#ifndef __HBC_CONTENT0_H__
#define __HBC_CONTENT0_H__
/* -------------------------------------------------------------------------------- */

extern const unsigned char hbc_content0[];
extern const int hbc_content0_size;

/* -------------------------------------------------------------------------------- */
#endif /* __HBC_CONTENT0_H__ */
/* -------------------------------------------------------------------------------- */

