/* RGD SDBoot Installer */

/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

/* -------------------------------------------------------------------------------- */
#ifndef __HBC_CERTS_H__
#define __HBC_CERTS_H__
/* -------------------------------------------------------------------------------- */

extern const unsigned char hbc_certs[];
extern const int hbc_certs_size;

/* -------------------------------------------------------------------------------- */
#endif /* __HBC_CERTS_H__ */
/* -------------------------------------------------------------------------------- */

