/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _hbc_content1_h_
#define _hbc_content1_h_
//---------------------------------------------------------------------------------
extern const unsigned char hbc_content1[];
extern const int hbc_content1_size;
//---------------------------------------------------------------------------------
#endif //_hbc_content1_h_
//---------------------------------------------------------------------------------
