/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _hbc_content0_h_
#define _hbc_content0_h_
//---------------------------------------------------------------------------------
extern const unsigned char hbc_content0[];
extern const int hbc_content0_size;
//---------------------------------------------------------------------------------
#endif //_hbc_content0_h_
//---------------------------------------------------------------------------------
