/* RGD SDBoot Installer */

/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

/* -------------------------------------------------------------------------------- */
#ifndef __HBC_CONTENT1_H__
#define __HBC_CONTENT1_H__
/* -------------------------------------------------------------------------------- */

extern const unsigned char hbc_content1[];
extern const int hbc_content1_size;

/* -------------------------------------------------------------------------------- */
#endif /* __HBC_CONTENT1_H__ */
/* -------------------------------------------------------------------------------- */

